Add reproducer for Project creation race bug
This patch adds a functional tests that reproduce the error

  sqlalchemy.exc.InvalidRequestError: This session is in 'inactive'
  state, due to the SQL transaction being rolled back; no further SQL
  can be emitted within this transaction.

that happens during two racing allocation update.

Co-Authored-By: melanie witt <melwittt@gmail.com>

Story: 2009159
Task: 43147

Change-Id: I80df62dae3a31481c71254e1054973df39bec955