Call Engine.execute() in func tests for oslo.db 11.0.0
Since the requirements bump of oslo.db from 10.0.0 => 11.0.0, the
functional test jobs are failing with errors like this:

  sqlalchemy.exc.UnboundExecutionError: This Insert is not directly
  bound to a Connection or Engine. Use the .execute() method of a
  Connection or Engine to execute this construct.

This adjusts the insert/update statements to execute through the
Engine.execute() method as is directed in the error message.

Story: 2009209
Task: 43268

Change-Id: I0aa33ed4b131d254a4ec5b8477660990e097b77b